#################################
# Backend GLX
#################################
backend = "glx";
vsync = false;

#################################
# GLX Performance
#################################
glx-no-stencil = true;
glx-copy-from-front = false;
glx-use-gpu = true;
glx-no-rebind-pixmap = true;
xrender-sync-fence = false;

#################################
# Damage & Unredirect
#################################
use-damage = true;
unredir-if-possible = false;

#################################
# Visual Minimal
#################################
shadow = false;
fading = false;
active-opacity = 1.0;
inactive-opacity = 0.9;
frame-opacity = 0.9;
inactive-opacity-override = false;
corner-radius = 6;
rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'Polybar'",
    "class_g = 'Rofi'"
];

blur-background = false;

#################################
# Animasi 
#################################
animations = true;
animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-stiffness = 3500;
animation-window-mass = 0.75;
animation-dampening = 15;
animation-clamping = true;

#################################
# Deteksi
#################################
detect-client-opacity = true;
detect-rounded-corners = false;
mark-wmwin-focused = false;
mark-ovredir-focused = false;
detect-transient = true;
detect-client-leader = true;
