#!/bin/sh

# Workspace
bspc monitor -d 1 2 3 4

# Layout
bspc config split_ratio 0.50

# Window spacing
bspc config window_gap 8
bspc config border_width 0

# Padding
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config border_radius 10

# Kill old processes
killall polybar 2>/dev/null
killall picom 2>/dev/null
killall sxhkd 2>/dev/null
killall snixembed 2>/dev/null

# Custom
export SXHKD_SHELL=sh >/dev/null 2>&1 &
xset s off >/dev/null 2>&1 &
xset s noblank >/dev/null 2>&1 &
xset -dpms >/dev/null 2>&1 &
xset dpms 0 0 0 >/dev/null 2>&1 &
feh --randomize --bg-fill ~/Wallpapers/ >/dev/null 2>&1 &
polybar -r -c ~/.config/polybar/bconfig.ini >/dev/null 2>&1 &
picom >/dev/null 2>&1 &
sxhkd >/dev/null 2>&1 &
snixembed >/dev/null 2>&1 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 >/dev/null 2>&1 &
