
;==========================================================
; macOS-inspired Linux Polybar
; Openbox + Picom
;==========================================================

[colors]

background      = #50181818
background-alt  = #00000000

foreground      = #F5F5F5
foreground-alt  = #B8B8B8

red             = #FF7777
green           = #A5E6A0

transparent     = #00000000


;==========================================================
; BAR
;==========================================================

[bar/macos]

width               = 100%
height              = 30

offset-x            = 0
offset-y            = 0

radius              = 0

background          = ${colors.background}
foreground          = ${colors.foreground}

border-size         = 0
border-color        = ${colors.transparent}

padding-left        = 8
padding-right       = 8

module-margin-left  = 0
module-margin-right = 5

fixed-center        = true

enable-ipc           = true

wm-restack           = generic
override-redirect    = false


;==========================================================
; FONTS
;==========================================================

font-0 = "Inter:style=Medium:size=10;2"
font-1 = "Inter:style=Bold:size=10;2"
font-2 = "JetBrainsMono Nerd Font:style=Bold:size=11;2"


;==========================================================
; MODULE LAYOUT
;==========================================================

modules-left   = linux workspaces
modules-center = clock
modules-right  = tray cpu memory network pulseaudio battery


;==========================================================
; LINUX
;==========================================================

[module/linux]

type = custom/text

format = <label>

label = "󰌽"
label-font = 2
label-foreground = ${colors.foreground}

click-left = rofi -show drun


;==========================================================
; WORKSPACES
;==========================================================

[module/workspaces]

type = internal/xworkspaces

enable-click = true
enable-scroll = true

format = <label-state>

label-active = " %name% "
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.background}
label-active-padding = 1

label-occupied = " %name% "
label-occupied-foreground = ${colors.foreground-alt}
label-occupied-background = ${colors.background}
label-occupied-padding = 1

label-empty = " %name% "
label-empty-foreground = ${colors.foreground-alt}
label-empty-background = ${colors.background}
label-empty-padding = 1

label-urgent = " %name% "
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.background}
label-urgent-padding = 1


;==========================================================
; CLOCK
;==========================================================

[module/clock]

type = internal/date

interval = 1

date = %a, %b %d
time = %H:%M

label = "%date%  %time%"
label-font = 1
label-foreground = ${colors.foreground}

;==========================================================
; TRAY
;==========================================================

[module/tray]
type = internal/tray
tray-background = ${colors.background}
tray-size = 70%

;==========================================================
; CPU
;==========================================================

[module/cpu]

type = internal/cpu

interval = 2

format = <label>

label = "󰍛  %percentage:2%%"
label-font = 2
label-foreground = ${colors.foreground}


;==========================================================
; MEMORY
;==========================================================

[module/memory]

type = internal/memory

interval = 2

format = <label>

label = "󰋊  %percentage_used:2%%"
label-font = 2
label-foreground = ${colors.foreground}

;==========================================================
; WIFI
;==========================================================

[module/network]

type = internal/network

interface-type = wireless

interval = 1

format-connected = <label-connected>

label-connected = "󰤨   ↓ %downspeed%  ↑ %upspeed%"
label-connected-font = 0
label-connected-foreground = ${colors.foreground}

format-disconnected = <label-disconnected>

label-disconnected = "󰤨   --"
label-disconnected-font = 0
label-disconnected-foreground = ${colors.foreground-alt}

;==========================================================
; AUDIO
;==========================================================

[module/pulseaudio]

type = internal/pulseaudio

use-ui-max = true

interval = 2

format-volume = <ramp-volume>  <label-volume>

label-volume = "%percentage%%"
label-volume-font = 2
label-volume-foreground = ${colors.foreground}

format-muted = <label-muted> 
format-muted-prefix = "󰝟   "
label-muted = "0%"
label-muted-font = 2
label-muted-foreground = ${colors.foreground-alt}


ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
click-right = pavucontrol


;==========================================================
; BATTERY
;==========================================================

[module/battery]

type = internal/battery

battery = BAT0
adapter = AC

poll-interval = 5

full-at = 100

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>

label-charging = "󰂄 %percentage%%"
label-charging-font = 2
label-charging-foreground = ${colors.green}

label-discharging = "󰁹 %percentage%%"
label-discharging-font = 2
label-discharging-foreground = ${colors.foreground}

label-full = "󰁹 %percentage%%"
label-full-font = 2
label-full-foreground = ${colors.green}


;==========================================================
; SETTINGS
;==========================================================

[settings]

screenchange-reload = true
pseudo-transparency = true
